install:
  commands:
    - curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    - unzip terraform_1.5.7_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version

