version: 0.2
phases:
  install:
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform_1.5.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

